### ISSUE TITLE
Hint: don't nest DEFUN

### ISSUE THREAD

**Issue by lispm** [Wafelack/polynomials#1]
Local functions in Common Lisp are defined by FLET and LABELS, instead. LABELS is used to define local recursive functions. 

DEFUN usually should only be used at 'top-level' and not inside normal code, since it then redefines a global function when executed.

**Comment by Wafelack** [comment]
OK, thanks for the tip, I'll fix that as soon as possible.

**Comment by lispm** [comment]
More hints:

you don't need to write (funcall #'get-arrow a T). Just write (get-arrow a T). FLET and LABELS bind functions in the function namespace.  Similar for (funcall #'check left).

You are using cons cells to return two values from a function (-> SOLVE, ALPHABETA). Common Lisp can return multiple values on the stack. See -> VALUES, MULTIPLE-VALUE-BIND.

**Comment by Wafelack** [comment]
Thanks for the `funcall` tip, the documentation I read made me think that it was the only way to do it.
I know about `values` but I thought it would be less verbose to use a pair. But it's true that it does a needless allocation. Thank you.
